version: '3.7'

services:
    php-httpd:
        image: php:7.3-apache
        ports:
            - 8080:80
        volumes:
            - "./src:/var/www/html"
            - "./config:/var/www/config"
